#ifndef ME_CONSTANTS_H
#define ME_CONSTANTS_H

#define ME_FPS 60

#define ME_WINDOW_WIDTH 640
#define ME_WINDOW_HEIGHT 480

#define ME_OK 1
#define ME_ERROR_SDL_INIT -1
#define ME_ERROR_WINDOW_INIT -2
#define ME_ERROR_RENDERER_INIT -3
#define ME_ERROR_TEXTURE_INIT -4
#define ME_ERROR_CANVAS_INIT -5
#define ME_ERROR_OBJECT_BAG_INIT -6
#define ME_ERROR_SCENE_MANAGER_INIT -7
#define ME_ERROR_SCENE_CREATE -8

typedef int MERet;

#endif//ME_CONSTANTS_H
